# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ahcer

on:
  push:
    branches:
      - main
      
env:
  AZURE_WEBAPP_NAME: ahcer   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './ahcer/dist/ahcer'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --prod
      working-directory: 'ahcer'

    - name: Deploy to Linode
      uses: appleboy/scp-action@master
      with:
        host: ahcer.org
        username: hammannr
        key: ${{ secrets.LINODE_PRIVATE_KEY }}
        source: dist/
        target: /var/www/html/ahcer.org/public_html
        working-directory: 'ahcer'
      
    #- name: 'Deploy to Azure Web App'
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #    publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa593239d6fa4e4c835cb8ed35585801 }}
    #    package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
